apiVersion: v1
kind: PersistentVolumeClaim

spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/postgresql/data"

metadata:
  name: postgres-pv-volume
  namespace: default
  labels:
    type: local
    app: postgres
