apiVersion: v1
kind: ConfigMap

data:
  REDIS_HOST: redis
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: db
  POSTGRES_USER: root
  POSTGRES_PASSWORD: mysupersecretpassword
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru

metadata:
  name: rediscfg
  namespace: default